# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dekoders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dekoderName', models.CharField(max_length=200, verbose_name='data publikacji')),
                ('serialNumber', models.DecimalField(decimal_places=0, max_digits=12)),
                ('dekoderVersion', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='data publikacji')),
            ],
        ),
    ]
