# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='karta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kartaName', models.CharField(max_length=200, verbose_name='Karta')),
                ('serialNumber', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='S/N')),
                ('kartaVersion', models.CharField(max_length=20, verbose_name='Typ')),
                ('kartaOwner', models.CharField(max_length=20, verbose_name='Wlasciciel')),
                ('kartaCurrentOwner', models.CharField(max_length=20, verbose_name='Obecny Wlasciciel')),
            ],
        ),
    ]
