# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaty', '0002_karta'),
    ]

    operations = [
        migrations.CreateModel(
            name='endurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dekoderName', models.CharField(max_length=200, verbose_name='Karta')),
                ('serialNumber', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='S/N')),
                ('RaVersion', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='S/N')),
                ('FWversion', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='S/N')),
                ('comment', models.CharField(max_length=1000, verbose_name='komentarz')),
                ('StartDate', models.DateTimeField(verbose_name='poczatek')),
                ('EndDate', models.DateTimeField(verbose_name='koniec')),
                ('statusField', models.IntegerField(choices=[(0, 'Pending'), (1, 'Done')], default=0)),
            ],
        ),
    ]
