# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaty', '0003_endurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endurance',
            name='EndDate',
            field=models.DateTimeField(null=True, verbose_name='koniec'),
        ),
        migrations.AlterField(
            model_name='endurance',
            name='FWversion',
            field=models.CharField(max_length=1000, verbose_name='SFW'),
        ),
        migrations.AlterField(
            model_name='endurance',
            name='RaVersion',
            field=models.CharField(max_length=1000, verbose_name='RA'),
        ),
    ]
