# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaty', '0004_auto_20170120_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endurance',
            name='EndDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='koniec'),
        ),
    ]
